#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Rocco Jiang"
email = "10642716+roccojiang@users.noreply.github.com"

[ui]
default-command = "log"

pager = "delta"
diff-formatter = ":git"
